export const apasionado = {
  title: "APASIONADO: Emotivo, Activo, Secundario",
  general: [
    "El individuo perteneciente a este tipo caracterológico no puede estar inactivo; pero esta actividad no es impulsiva y voluble, sino enérgica. sin embargo. se exterioriza poco; por ello, cuando se desborda es violenta y avasalladora. Sabe recordar las lecciones de experiencias pasadas y aprovecharlas en el futuro. Su iniciativa y acometividad son muy grandes, aunque calmadas en el exterior, salvo casos excepcionales y dirigidas conscientemente a fines lejanos y constantes.",
    "Sus sentimientos y pasiones son fuertes, profundizan hondamente y arraigan en él, influyendo en su conducta durante mucho tiempo. Ante las injurias su coraje se enciende interiormente, aunque no se exterioriza en seguida, si se repiten. al final estalla en una tempestad de ira duradera que fácilmente deriva hacia el rencor y deseo de venganza.",
    "Ante el peligro, reflexiona primero y pronto toma una determinación; si se decide a atacar, procederá con violencia inaudita hasta vencer o morir; si juzga que debe tomar la actitud pasiva es tenaz en tal postura.",
    "Las faltas propias y ajenas le causan gran enojo y se propone con firmeza corregirlas Es constante en la acción, inmutable en sus juicios, a veces hasta la testarudez. Posee sentimientos estables de tal modo que su amistad es fidelísima aún después de largo tiempo, pero también le cuesta olvidar una ofensa y perdonar.",
    "Tiene notable capacidad de organización y mando no tanto simpático y atrayente cuanto eficaz, vigoroso y ordenado. Enérgico y sin gran peligro de dispersión, sabe ser firme, sistemático y orientado hacia un fin, al que se acerca por etapas bien meditadas.",
    "Su inteligencia es amplia y más bien deductiva; su imaginación fecunda y a menudo goza de excelente memoria. Le interesan los problemas sociales, mora les, religiosos filosóficos. Es naturalmente honrado y digno de confianza. Sabe ser fiel a su palabra. Con respecto a los menos dotados adopta espontáneamente una actitud de protección y ayuda compasiva. En la vida social se muestra digno, ordenado y sencillo sin gran inclinación por la diplomacia sinuosa, pero tampoco por el choque brusco; exteriormente es correcto por lo general, aunque poco efusivo.",
  ],
  positive: [
    "Cuando se encauza hacia un ideal grande, es capaz de una consagración, abnegación y actividad extraordinaria. Su rigor lógico en el pensamiento, su memoria, capacidad de invención y eficacia en la ejecución le capacitan para las grandes empresas, en cuya dirección o alta jefatura puede conseguir notables objetivos. Toma sus propios asuntos y los que le encomiendan con mucha seriedad, y es de fiar cuando empeña su palabra o promete alguna cosa. En la dirección de los súbditos sabe unir la exactitud aunque a veces le falta algo de simpatía atrayente; al final, sí es consecuente con su natural rectitud, se impone por su justicia y nobleza. No olvida los favores y es agradecido. Es notable su poder de previsión y sentido de responsabilidad. Es un director o jefe nato, con tendencia afectiva y fundada hacia los grandes planes y objetivos. No está hecho para las cosas de poca importancia. Sus aspiraciones son siempre grandes, en cualquier campo a que se dedique. Toma en serio su vocación y le gusta resolverla reflexivamente. Desde el punto de vista caracterológico, es apto para casi todas las carreras superiores menos para el arte.",
    "Si se encauza bien su vida espiritual tiene dotes para un fecundo apostolado y no se contentará con mediocridades, sino que aspirará a la auténtica santidad.",
  ],
  negative: [
    "Sus defectos presentan los mismos matices que sus buenas cualidades: grandes pasiones que no se borran fácilmente. Encuentra dificultad en sujetarse a un superior.",
    "Puede ser susceptible. crítico, desconfiado, así como volverse huraño y poco social si acentúa en sí su actitud espontánea de reserva. Cuando odia lo hace de todo corazón y es difícil hacerlo reconciliar con su enemigo. Tiende espontáneamente al rencor y la venganza.",
    "Otro de sus defectos capitales es la testarudez: cuando se forma un juicio sobre una cosa, es casi imposible hacerle cambiar dé parecer. Naturalmente, si se equivoca han de atenerse a las consecuencias.",
    "Como su pasión, con frecuencia le oscurece el juicio, sus críticas son severas, y muchas veces injustas. Es también notable su amor propio, ya que no consiente ser vencido ni sobrepasado por nadie. No es raro que se note en él impaciencia respecto a los defectos ajenos y desconfianza hacia algunas personas. En la acción peca a menudo por exceso de energía lo que lo lleva a ser duro y exigente con los otros.",
  ],
};

export const colerico = {
  title: "COLERICO: Emotivo, Activo, Primario",
  general: [
    "Es tal vez su nota más distintiva el deseo de actividad exuberante: una necesidad vital de hacer algo, y esto de un modo impulsivo. No se siente satisfecho sino en una ocupación donde pueda descargar su ímpetu vital. Es combativo, proselitista, persuasivo en sumo grado y entusiasta; emprendedor de gran iniciativa. Por lo general optimista y alegre y aunque pasa fácilmente y con rapidez de unos sentimientos a otros, su gran acometividad le suministra continuamente entusiasmo y fogosidad para el desarrollo de sus actividades. Muchas veces esa actividad es febril, sin gran constancia en una misma dirección ni profundidad en su trabajo.",
    "Sus sentimientos son abundantes, fuertes, expansivos en sumo grado. Tiene inclinación innata a comunicar lo que piensa y siente, para lo que le ayuda su relevante facilidad de palabra. Todas sus pasiones tienen este matiz marcado de extremos, es propio para las grandes empresas, ya que no puede resignarse con miras estrechas ni términos medios",
    "Ante las injurias reacciona violentamente de palabra y pasa a las obras sin esperar repetidas incitaciones. En los momentos de peligro se exalta y llena de entusiasmo, lanzándose a la acometida sin pararse mucho a calcular las consecuencias. Cuando ha cometido una falta se llena de indignación consigo mismo. Ante las faltas ajenas no sabe despreocuparse: las reprende y pone lo que está de su parte porque se corrijan usando los medios más eficaces.",
    "Tiene instinto de mando y dominación y se contenta difícilmente con el puesto de súbdito. Su inteligencia es rápida y penetrante, predominante intuitiva, no pocas veces de vasta capacidad.",
    "Todo su porte exterior suele estar de acuerdo con su modo de ser: facciones varoniles, mirada decidida, paso firme y movimientos enérgicos.",
  ],
  positive: [
    "Su natural fortaleza, audacia y valentía le capacitan para grandes empresas. Es hombre de ideales elevados, a los que ende reza sus energías, y, por ello, no se queda con pequeñeces ni medianías. Todo lo cual lo capacita, presupuestas otras cualidades de inteligencia, etc. para desempeñar cargos de importancia en la vida social. Cuenta con una voluntad decidida y una amplitud de miras muy grandes, que le permite extender sus actividades a muy diversos campos. Ha sido éste el carácter peculiar de muchos jefes, dadas sus cualidades de mando y conquista combinadas con un ánimo generoso y magnánimo.",
    "Apto para la política, la enseñanza, periodismo, la dirección de colectividades, tiene gran talento de improvisación y cualidades de orador. Con frecuencia organiza acertadamente las actividades del grupo social a que pertenece y en ello sabe seducir con su optimismo comunicativo.",
    "Aficionado al deporte, suele cosechar en él no pocos éxitos.",
    "En la vida espiritual puede llegar a notable grado de santidad, ayudado de la gracia divina.",
  ],
  negative: [
    "Su temperamento le lleva a vivir el instante presente interesándose exclusivamente por los resultados inmediatos. Tiene además un gran peligro de dispersión y derroche de su caudal vital empezando muchas cosas sin acabarlas o comprometiéndose a más tareas de las que podrá realizar o simultáneamente teniendo varias ocupaciones sin llevar bien ninguna de ellas.",
    "Bajo el dominio de su natural impulsividad, puede tomar fácilmente decisiones arriesgadas, que le conduzcan a situaciones comprometidas por no haber calculado con previsión las consecuencias.",
    "Su riqueza psicológica y el reconocimiento (le su propia superioridad en la acción le pueden llevar muy fácilmente al orgullo o por lo menos a la vanidad y a hacerle difícil el reconocer superiores. Confía en si mismo y quiere siempre imponer su voluntad a los demás. Le cuesta reconocer sus defectos y fácilmente crítica los ajenos, siendo indulgente consigo mismo y exigente con los demás. Puede llegar a defender sus defectos como si fueran buenas cualidades y aún a gloriarse de sus faltas. Esto hace que su caída sea más ignominiosa y más costosa su recuperación moral. También es posible que llegue a ser tan irascible que no pueda dársele el menor motivo de enfado porque en seguida se desata la tempestad de cólera que llega a veces hasta la crueldad.",
    "Otro peligro en su acción es, el desear vivamente sus fines, que para conseguirlos llegue a usar medios indignos.",
  ],
};

export const sentimental = {
  title: "SENTIMENTAL: Emotivo, No Activo, Secundario",
  general: [
    "Profundidad y perseverancia de sentimientos, los cuales, sin embargo, se manifiestan poco exteriormente. Almas muy sensibles a toda clase de emociones o impresiones externas, la reacción íntima se concentra en el fondo del alma y allí se graba tenazmente y hasta se acentúa cada vez más. Por ejemplo, cuando se recibe una ofensa no es raro que aparezca exteriormente como poco impresionado pero, una vez solo saboreará su resentimiento agrandando tal ofensa imaginativamente. Si se repiten las injurias llegará un momento que estalle violentamente con reconciliación difícil, por la profundidad de la herida en su espíritu. Por otra parte, en la amistad es fiel y constante. No suele tener muchos amigos y prefiere un pequeño grupo de íntimos. Recuerda y agradece cualquier favor y atención que con él se tuvo No muy propenso a la risa y expansión, lo es mucho a la seriedad y aún melancolía o escrúpulos.",
    "Su fuerte no es la actividad física ni intelectual, sino la afectividad. Fácilmente conmovido por los males ajenos y viendo tantas miserias en el mundo quisiera remediarlas. Puede entonces, acongojarse por dos cosas: su dificultad en la expresión exacta de sus sentimientos (lo que lo invita a encerrarse dentro de sí mismo), y el poco potencial dinámico que experimenta para la acción. Procura evitar todo lo que piensa le va a herir interiormente En su trato con los demás. No es raro que sufra más que otros por los defectos ajenos dada su sensibilidad que puede hacerle susceptible.",
    "Sumamente propenso a la reflexión y el análisis de si mismo. Indeciso, vuelve mil veces sobre sus sentimientos y acciones, lo que, junto con su profundo sentido moral le impide en muchas ocasiones seguir adelante y actuar . Siempre teme no haber hecho las cosas bien y de un modo recto. En la acción es más bien lento y no suele emprender obras por iniciativa propia. En momento de peligro prefiere más bien una actitud pasiva que activa en la defensa. Ante sus propias faltas se desanima con facilidad y desespera en corregirse, ante las ajenas se subleva interiormente, aunque muchas veces no acierta a ponerles remedio. No gran sentido práctico, soñador, muchas veces buen literato amigo de escribir diario intimo. Frecuentemente sensible a los cambios meteorológicos.",
    "Tiene seria concepción de la vida y en general ama todo lo grave y profundo. Su actitud ordinaria es de dulzura y amabilidad exterior. aunque no suele ofrecerse espontáneamente, ayuda cuando es requerido. Muy apto para las obras que exijan consagración, silencio y caridad. Su perseverancia es una característica marcada. Cumplidor de su deber, se da cuenta de sus responsabilidades y procura atenderlas con esmero. Es de apariencia sencilla y poco amigo de ostentación.",
  ],
  positive: [
    "Sobresale en él la bondad y honradez. Incapaz de ser cruel o áspero con otros aunque externamente su reserva parezca apatía. Con frecuencia le agrada el cuidado de los enfermos. compensa su escasa tendencia a la acción con su facilidad para la oración. En general, encuentra consuelo y paz interior en el trato intimo con Dios. Sencillo, humilde y fidedigno poco inclinado a la sensualidad. Propenso a ayudar a los demás. Perseverante. Trabaja con profundidad y acepta generosamente sus obligaciones.",
    "Suele tener disposiciones para matemáticas y lenguas y también para aquellas ciencias que exigen minuciosos análisis de acciones humanas. Abundan en este tipo los moralistas, pedagogos, psicólogos, etc., así como los literatos y críticos de arte.",
  ],
  negative: [
    "Tiene el peligro de pecar siempre por defecto, por indecisión ante un partido que hay que tomar. Tiende al desánimo y a subestimar sus propias cualidades, con ello puede llegar a un pesimismo, amargura o timidez molesta para si mismo y para los demás. Y como compensación puede habituarse a juzgar y calificar interiormente al prójimo con falta de caridad. No es raro el peligro de orgullo y soberbia interior afectiva, como compensación también de sentirse inferior respecto a otros cuya acción y apariencia es más brillante. Encuentra gran dificultad en perdonar las ofensas y cuando odia lo hace intensamente. Por una injuria recibida se siente despreciado y odiado, desconfía de todos y juzga que le quieren hacer mal. Aficionado a falsear mentalmente (huyendo de la acción y de realizar su porvenir) corre el riesgo de agriar su carácter si cede excesivamente a su tendencia a la soledad, lo que puede hacerle egoísta.",
  ],
};

export const nervioso = {
  title: "NERVIOSO: Emotivo, No Activo, Primario",
  general: [
    "Abundancia de sentimientos sujetos a una gran variabilidad. En un momento recorre toda su vasta gama emotiva sin que ello deje huella duradera. Por lo mismo, su vitalidad es tumultuosa, poco coherente y ordenada. Esto y la excitabilidad le dan la apariencia de una impulsividad grande pero todas estas expresiones e ímpetus no llegan a cristalizar casi nunca en realidades activas. Su vida subjetiva, rica y compleja es lo que más atrae su interés: hombre de problemas interiores, tensiones, intensos goces y sufrimientos que se suceden unos a otros y le hacen pensar mucho en si mismo. Pero esta variedad de sentimientos no constituye una regla infalible para todos los casos: pueden ser tan repetidos los estímulos y tan viva la sensibilidad, que se mantengan las impresiones durante largo tiempo, aunque viene ello a suceder más por esa renovación constante que por tender de suyo a la permanencia.",
    "Su imaginación es vivísima y su ingenio viva. Artista por naturaleza con frecuencia posee talento musical, casi siempre notable facilidad de palabra y aún dotes literarias. La profusión de imágenes unida a su fina sensibilidad, le hacen en extremo sugestionable convierte la menor impresión en un sensación inmensa, realista. Curioso en extremo, ama lo que le causa placer momentáneo, lo impresionante. Siente vivamente las injurias y da muestras de ello con alteraciones de genio, aunque pasajeras. Esta excitabilidad puede hacerle muy indisciplinado, rebelde y rudo en el trato con quienes lo hieren (o cree él que le ofenden, pues fácilmente es suspicaz y tacha a los demás de injustos para con él). Su imaginación le agiganta los peligros y se acobarda con facilidad, sin embargo, es amigo de aventuras fantásticas y estrambóticas. Cuando ha cometido alguna falta cae en un gran postración y hace propósitos de corregirse, pero pronto se olvida de ellos. También tiende a sobrevalorarse a sí mismo, subrayando mentalmente sus buenas cualidades y prestando poca atención a sus defectos cuando éstos no le han llevado a algún fracaso reciente y doloroso. Siente como una necesidad interior de llamar la atención, de ser admirado, así como desahogar sus frecuentes arrebatos o impulsos.",
    "Su inteligencia no suele ser muy amplia en su objetivo: es de tipo más bien intuitivo que deductivo, más concreto que abstracto. En la actividad es ágil, sus nervios están siempre tensos, pero no persevera mucho en su esfuerzo continuo y penoso. Altamente influenciable por los amigos o por el ambiente social, tiende a pensar, sentir y actuar con rapidez por su gran capacidad de sintonía psíquica. Ello le hace muy adaptable a los nuevos ambientes. Sabe ejercer sobre los demás cierta seducción pues suele ser de trato muy simpático con quienes congenian con él.",
  ],
  positive: [
    "Tiene un corazón muy sensible a los males de los demás, así como a los favores que se le hacen y atenciones de que es objeto. Es inclinado a la bondad y compasión y sumamente generoso. Nadie tan atento como él respecto a las necesidades y gustos ajenos, con una servicialidad espontánea y cariñosa cuando trata con aquellos a quienes admira o sabe que la aprecian y quieren. Posee fino tacto y sabe ser diplomático cuando lo desea. Si le mandan a alguien a quién aprecia como superiores dócil y obediente. Su espíritu delicado le comunica una gracia y don especial para el trato. Pocos tan aptos para consolar a una persona abatida.",
    "Son notable, por lo general, sus dotes de reacción subjetiva y suele poseer un gusto para intuir el mensaje de los otros artistas.",
  ],
  negative: [
    "Donde está la raíz de sus virtudes naturales, está también la de sus defectos: su sensibilidad. Los demás para tratarle, se ven obligados muchas veces a examinar previamente su humor. Si se deja dominar por sus sentimientos se hace insoportable a sus compañeros. Puede llegar a ser tan susceptible que si se le mira se siente quizás herido porque le miramos y si no se le mira porque se siente despreciado. Inclinado también a la vanidad y a la sensualidad. Vive de impresiones, de ímpetus momentáneos; si se abandona a ellos no realizará nada grande y serio. Es imprevisor y enemigo de todo lo que exija esfuerzo y disciplina metódica (mental o física). Esta inconstancia es su defecto principal. Además por tal dependencia de la impresión momentánea, fácilmente cambia de parecer y de ocupación puede llegar a ser esclavo del momento presente (lo que otros dicen o hacen, bueno o malo) y corre serios peligros si no se cohíbe su afán de nuevas emociones y aventuras.",
  ],
};

export const hermetico = {
  title: "HERMETICO: No Emotivo, Activo, Secundario",
  general: [
    "Presenta una personalidad vigorosamente estructurada sin quiebres, con un fondo riquísimo de energía activa. No tiene sentimientos intensos pero si, constancia y tenacidad en la acción.",
    "Hombre sin grandes pasiones, difícilmente excitable se mantiene en constante tranquilidad afectiva. En la acción raramente violento o sobre excitado. Sumamente paciente. Poco hablador, cuando se comunica lo hace con medida y casi nunca elevando la voz. Reduce a la mínima expresión las manifestaciones de afecto dando muchas veces sensación de frialdad. Continuamente ocupado, minuciosamente ordenado y metódico en todo su proceder. No suele gustar de la vida social aunque es fiel a las amistades.",
    "Espíritu claro y lógico, sus intereses preponderantes son más bien intelectuales: estudio especulativos, matemáticas, jurídicas, literatura. Poco intensas sus inclinaciones eróticas, no suele ser propenso a la sensualidad, es sencillo en sus cosas y rara vez vanidoso.",
    "Sus obras están de acuerdo con sus ideas y principios. Muestra gran rectitud moral, casi inflexible. Reflexivo y sumamente prudente, no se decide a ninguna empresa hasta no haber calculado las últimas probabilidades de éxito, ponderando todas las dificultades. Una vez decidido, se dedica con seriedad y constancia al trabajo.",
    "Ahorrador, honrado, y sincero, no se inmuta ante las ofensas, no se da por enterado, o las toma con humor alegre. En momentos de peligro es indeciso aunque no se turba fácilmente, conserva su serenidad pero no se resuelve con prontitud. Si comete alguna falta no se angustia demasiado.",
    "Su inteligencia es más apta para profundizar que para pensar con rapidez. Sobresale por su sentido práctico y conocimiento de las personas. Buen organizador, objetivo y realista, tiene poco vigor imaginativo y no es muy inclinado a la creación artística.",
  ],
  positive: [
    "Suele ser notable su tranquilidad en recibir todos los acontecimientos sin angustiarse por las dificultades ni preocuparse inútilmente. Conserva fácilmente el equilibrio entre el pensar y el obrar, entre el sentimiento y la acción. Sin pasiones violentas, es sobrio y moderado y no se deja llevar por sus primeros impulsos. Amigo de la reflexión y de la consideración lenta de las cosas, es de pensamiento maduro y profundo en sus convicciones religiosas y criterios fundamentales.",
    "Paciente en tolerar a los demás, sus sentimientos fácilmente son de benevolencia y amabilidad. Poco inclinado a la pompa y al brillo es natural y sencillo, sin ambiciones exageradas. No suele mentir nunca. Lo que no logra por una actividad rápida lo alcanza por su constancia. Hombre práctico sabe aprovechar los medios y busca más lo útil que lo llamativo. Le gustan las obligaciones netamente definidas. Apto para todo lo que requiere orden y constancia tiene por ello dotes de grn colaborador. Esto y su hondo sentido del deber le capacitan para cargos directivos de gran responsabilidad social y delicada administración. En sus trabajos suele ser eficiente, seguro y asiduo.",
  ],
  negative: [
    "Su tranquilidad sentimental puede degenerar en una especie de apatía despreocupándose de todo sin mostrar interés o entusiasmarse por cosa alguna. Ello suele endurecer notablemente su corazón haciéndole insensible y frío para con los demás y llevándole paulatinamente a un egoísmo calculador y al orgullo por autosuficiencia.",
    "Tiende a ser esclavo de su organización, costumbre y método. Por su parte, es posible que exagere su prudencia y previsión hasta el extremo de no comenzar nada por pensar demasiado las posibles dificultades desaprovechando así las ocasiones propicias. Ello le hace acobardarse en más de una ocasión y lo que es paradójico en u carácter activo puede hacerle perezoso al rehuir la acción por evitar sus posibles fracasos o peligros, o sencillamente por defender su soledad e independencia del ajetreo y trato social. En estos casos suele refugiarse en la actividad mental (preferentemente imaginativa) prefiriendo sistemáticamente en su acción exterior lo cómodo y fácil alejándose de cuanto pueda parecer difícil o arduo.",
  ],
};

export const sanguineo = {
  title: "SANGUINEO: No Emotivo, Activo, Primario",
  general: [
    "Abundancia de sentimientos y sensaciones que son profundas e intensas y se sacuden unas a otras con gran rapidez. No puede estar inactivo aunque no suele ser constante en continuar lo comenzado. Generalmente está siempre alegre, sonriendo, muy locuaz, de viva y animada charla. Amigo de exagerar, de hacer ruido, de la animación por los demás. Sociable, atento y cortés, gusta del compañerismo y las amistades. Ama la libertad. En política y religión no se apasiona, en general sus pasiones no son muy fuertes. Suele tener disposición para la música y gusto en los deportes. Su imaginación activa, aunque necesita ocupación continua, prefiere lo más agradable, gustoso y llamativo. Se deja llevar fácilmente por las apariencias y por ello con frecuencia es superficial en sus juicios. Para perseverar en una obra comenzada necesita siempre nuevos estímulos, desea variar siempre, y por eso, en su generosidad difícilmente llega al don total.",
    "Expansivo y efusivo, todo lo dice, lo comenta y discute, y comunica a los demás. No se irrita fácilmente ante las ofensas, y silo hace, pronto se lanza sin reflexionar y no es fácil acobardarle. Cuando ha cometido alguna falta fácilmente se consuela y renueva los buenos propósitos.",
  ],
  positive: [
    "Es persona de agradable trato en la vida social. Afable, bondadoso lleno de alegría y de buen humor, animoso y comunicativo, muy servicial y cortés con todos. Fácil mente cae en la cuenta de lo que le hace falta a los demás y con agrado presta su ayuda. Compasivo y misericordioso para con las debilidades ajenas. Posee notable sentido práctico e inteligencia intuitiva. Suele tener disposición para la música y gusto en los deportes. A veces tiene buenos dotes literarios (es descriptivo y humorista, más que lírico y profundo>.",
    "No se preocupa con angustia ni ahonda demasiado en los problemas. Tiene tacto para reprender las faltas ajenas con delicadeza, pero con sinceridad. Amigo de decir siempre las verdades, poco partidario de simulaciones. No guarda rencor para nadie. Perdona fácilmente. Muy dócil a las indicaciones de los superiores, con sencillez de espíritu.",
  ],
  negative: [
    "Su mejor victoria ha de ser la de acostumbrarse a reflexionar mucho y dar solidez a sus principios religiosos y mora les. Propóngase meditar y pensar muy bien lo que va a hacer y así obrar no arrastrado por el gusto ni por los primeros ímpetus, sino gobernado por la razón. De esta manera adquirirá más consistencia en la acción.",
    "La seriedad en los estudios le ayudará mucho a ser reflexivo. Los mismos deportes con la disciplina física que exigen, le serán muy provechosos, propóngase en su actividad objetivos fijos y concretos. Después no los cambie ante la primera ocurrencia o dificultad en contra.",
    "Por otra parte, es necesario que se decida a mortificarse en sus sentidos con gran empeño, si no quiere llegar a extremos muy lamentables. Para ello prívese de algunas comodidades, haga trabajos costosos y aún humildes en obras de cooperación y de caridad. Refrene sus apetitos e imaginación de manera metódica y constante, le ayudará mucho su predisposición natural a la bondad, así como el consejo de un buen director.",
    "Importante es que no se deje guiar por cualquiera que a primera vista parezca atrayente y simpático, sino por los buenos cumplidores del deber que tengan una personalidad más sólida y seria.",
    "Fomente y desarrolle sus excelentes dotes de servicialidad, trato amable, huyendo del egoísmo para hacer grata la existencia a los demás y llevarlos al bien con verdadera preocupación apostólica.",
  ],
};

export const apatico = {
  title: "APATICO: No Emotivo, No Activo, Secundario",
  general: [
    "Se acusa de deficiencia fisiológica de su vitalidad. La secundariedad Inactiva hace que prefiera la soledad, y por eso mismo declina las invitaciones a juegos y reuniones. Su aislamiento no se debe al deseo de llevar la contraria, sino que evita por su mismo carácter el mezclarse en el trato y actividad de los otros. No es que los compañeros le causen fastidio, sino que no suelen significar nada para él, no despiertan ningún encono en afectividad. Son innumerables en este carácter los tipos intermedios. Posee también la docilidad pero aparente, la causa de ello se debe buscar también en la poca tensión afectiva. La falta de simpatía por los demás que se nota en él, muy pocas veces se convierte en positiva antipatía. Aparece exteriormente digno, permaneciendo, sin embargo, enigmática la intimidad de su persona. Prefiere la vida tranquila, independiente del ajetreo social. No muestra gran inclinación por los trabajos prácticos, sino que tiende más bien a lo teórico. Como es dócil y conformista por esencia, se acomoda al régimen de vida del grupo al que pertenece aunque la asimilación de las nuevas costumbres es más bien lenta, arraigarán profundamente en su espíritu buenos hábitos y costumbres ordenadas. Lo contrario, y ello es grave peligro, sucederá si el ambiente es adverso a tal formación moral y social.",
  ],
  positive: [
    "En la fórmula caracterológica aparece como elemento positivo la secundariedad (fijeza, arraigo, tenacidad). Es capaz de disciplina y regularidad por automatización de las influencias del medio ambiente en que vive. No suele chocar con los demás. Su campo predilecto es el de la abstracción y le agradan las matemáticas más bien que las ciencias experimentales o trabajos prácticos. Suele tener aficiones pictóricas (dibujo, libre, etc.) y se encuentra bien en actividades uniformes y tranquilas.",
  ],
  negative: [
    "Se podrían reducir a la falta de dinamismo psíquico que casi siempre supone un desequilibrio del sistema neurovegetativo y, por consiguiente, una probable insuficiencia endocrina. Tiende a no preocuparse ni de sí mismo ni de sus compañeros, a vivir pasivamente. Por su reserva, su aire meditativo, simula cierta riqueza interior. Pero hay peligro de que se trate sólo de un disfraz y en realidad carezca de interés y entusiasmo en su vida. También puede polarizarse en su interés hacia un egocentrismo cerrado en que sólo le atraiga su bienestar propio, cuidarse y gozar. Por ello tiende a no comprometerse en actividades altruistas que exijan esfuerzo y sacrificio.",
  ],
};

export const amorfo = {
  title: "AMORFO: No Emotivo, No Activo, Primario",
  general: [
    "Muy rara vez se encuentra realizada esta fórmula en toda su plenitud y tiende a conjugarse con características de otros tipos al acentuarse la emotividad o actividad del sujeto.",
    'Muy influenciable por el ambiente. Optimista "buen mozo” y amable en el trato, notablemente sugestionable. Sociable, pero con tendencia a rehuir el esfuerzo personal que exijan los trabajos comunes. La falta de actividad en los tipos radicales y en el subtipo emotivo se manifiesta por la pereza. En el subtipo activo esta pereza está disfrazada. Los primeros "aceptan" las actividades (no las organizan) se dejan llevar, etc., por el ambiente. Los del segundo subtipo cumplen dócilmente un deber obligatorio a condición de que lo exija una autoridad fuerte, pero no hacen más que lo obligatorio dejando el esfuerzo para el último momento.',
    "Se fatiga pronto y tiene poco sentido de lo real. Gusta mucho del afecto del hogar, aunque no se siente atraído por la vida metódica y ordenada.",
  ],
  positive: [
    "Son ordinariamente valientes, no con valentía de conquista, sino que pasiva y resistente. Imperturbables ante el peligro. Es una verdadera cualidad que puede engendrar estima de sí mismo y voluntad de afirmarse en otros campos. Suelen tener entendimiento práctico y son de extrema sociabilidad, necesitan de los otros para actuar, lo hacen con gusto y no pocas veces con verdadera aptitud en el arte escénico. Con frecuencia poseen de ejecución musical.",
  ],
  negative: [
    "El defecto más notable es la pereza. Por eso mismo deja el esfuerzo para el último momento hasta que las necesidades le obliguen. Naturalmente esto le hace ser con frecuencia incumplidor e impuntual. Muchas veces esta pereza depende de causas orgánicas (astenia constitucional o accidental). Es más bien desmañado para las cosas que requieren orden. Negligente y a veces descuidado en la limpieza. Se deja influenciar fácilmente por el ambiente en que vive, y ello pude ponerle en serios peligros. Su inactividad es un obstáculo para la servicialidad, haciéndole cada vez más egocéntrico. Tiene el peligro de volar siempre a ras de suelo.",
  ],
};
